# Site settings
title: Elizabeth Myles
description: |
  a writer from Texas
owner: Elizabeth Myles # or company name
first_published: 2011 # if migrating another site, the year of your first publish
email: elizabeth@mylesandmyles.info
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.elizabethmyles.com" # the base hostname & protocol for your site
future: true

social:
  email: /contact/
  amazon: https://www.amazon.com/Elizabeth-Myles/e/B004Q2DZBY
  goodreads: https://www.goodreads.com/tangentuniverse
  bookbub: https://www.bookbub.com/profile/3421192761
  facebook-official: https://facebook.com/elizabethmyleswrites
  tumblr-square: https://fearandlaundry.mylesandmyles.info/
  tumblr: https://elizabeth.mylesandmyles.info/
  wordpress: https://mylesaweek.wordpress.com/
  pinterest: https://pinterest.com/tangentuniverse
  instagram: https://www.instagram.com/mrs.elizabethmyles/
 
# Build settings
reading_time:       true
words_per_minute:   200
permalink: /:categories/:title/

# Google services
google_analytics: UA—15892472-11

markdown: kramdown
#sass:
#  style: compressed
